/** These fields are stored and recovered when the application opens up */
export type PersistentPreferenceFields =
  | 'zoomFactor'
  | 'theme'
  | 'scrollbarsStyle'
  | 'isOutlinerOpen'
  | 'isInspectorOpen'
  | 'areFileEditorsDocked'
  | 'isFileTagsEditorOpen'
  | 'isFileExtraPropertiesEditorOpen'
  | 'thumbnailDirectory'
  | 'taggingServiceURL'
  | 'taggingServiceParallelRequests'
  | 'importDirectory'
  | 'method'
  | 'thumbnailSize'
  | 'thumbnailRadius'
  | 'largeThumbFullResThreshold'
  | 'masonryItemPadding'
  | 'thumbnailShape'
  | 'upscaleMode'
  | 'galleryVideoPlaybackMode'
  | 'showTreeConnectorLines'
  | 'hotkeyMap'
  | 'thumbnailTagOverlayMode'
  | 'inheritedTagsVisibilityMode'
  | 'isThumbnailFilenameOverlayEnabled'
  | 'isThumbnailResolutionOverlayEnabled'
  | 'outlinerWidth'
  | 'outlinerExpansion'
  | 'outlinerHeights'
  | 'inspectorWidth'
  | 'recentlyUsedTagsMaxLength'
  | 'recentlyUsedTags'
  | 'isClearTagSelectorsOnSelectEnabled'
  // startup options
  | 'isRefreshLocationsStartupEnabled'
  | 'isRememberSearchEnabled'
  // the following are only restored when isRememberSearchEnabled is enabled
  | 'isSlideMode'
  | 'firstItem'
  | 'searchRootGroup';
